language: node_js

sudo: false

node_js:
- 11

before_install:
- |
    if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(\.md$)|(^(docs|examples))/'
    then
      echo "Only docs were updated, stopping build process."
      exit
    fi
    npm install
    npm install -g codecov

script:
- |
    if [ "$TEST_TYPE" = test ]; then
      npm test
    else
      npm run $TEST_TYPE
    fi
env:
  matrix:
  - TEST_TYPE=lint
  - TEST_TYPE=coverage

after_success:
  - codecov

branches:
  only:
    - master

notifications:
  webhooks: https://oapi.dingtalk.com/robot/send?access_token=fe13eaac0e256bce410fd755deaa489f89cc3ce7969a0db9ebfc9354e2296b90
  email:
    - lb.robin1991@gmail.com